package com.example.xiaofu.mvp.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.xiaofu.mvp.model.db.DataGreenDao;

import com.example.xiaofu.mvp.model.db.DataGreenDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataGreenDaoDaoConfig;

    private final DataGreenDaoDao dataGreenDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataGreenDaoDaoConfig = daoConfigMap.get(DataGreenDaoDao.class).clone();
        dataGreenDaoDaoConfig.initIdentityScope(type);

        dataGreenDaoDao = new DataGreenDaoDao(dataGreenDaoDaoConfig, this);

        registerDao(DataGreenDao.class, dataGreenDaoDao);
    }
    
    public void clear() {
        dataGreenDaoDaoConfig.clearIdentityScope();
    }

    public DataGreenDaoDao getDataGreenDaoDao() {
        return dataGreenDaoDao;
    }

}
